### ISSUE TITLE
Favicon is hard to see in dark theme

### ISSUE THREAD

**Issue by yoasif** [kun-fang/set-aside-tabs#1]
Noticed that setting the dark theme in my OS makes the favicon used by set-aside-tabs to be very hard to see.

Ideally, when using a dark mode, set-aside-tabs would use an icon in white instead of black to make it easy to see.

![paveikslas](https://user-images.githubusercontent.com/152493/85879020-a2fafa80-b7a7-11ea-998f-183f344617ac.png)

**Comment by kun-fang** [comment]
I don't know how to change icons or icon color based on different browser theme, so the work around is to use a color icon. Updated the icons in the recent version.
